In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('iris.data',header=None)
#print(df)
x=df.iloc[0:100,[0,1,2,3]].values
y=df.iloc[0:100,4].values
y=np.where(y=='Iris-setosa',0,1)
#print(y)

In [3]:
x_train=np.empty((80,4))
x_test=np.empty((20,4))
y_train=np.empty(80)
y_test=np.empty(20)
x_train[:40],x_train[40:]=x[:40],x[50:90]

In [4]:
x_train_mean=np.mean(x_train,axis=0)
x_train_std=np.std(x_train,axis=0)
print(x_train_mean)
print(x_train_std)

[5.52375 3.11    2.89    0.79125]
[0.65864326 0.47712682 1.46676515 0.58141933]


In [5]:
# X input data standardization
x_train=(x_train-x_train_mean)/x_train_std
print(x_train)
x_test[:10],x_test[10:]=x[40:50],x[90:100]
x_test=(x_test-x_train_mean)/x_train_std
print()
print(x_test)

[[-0.64336801  0.81739275 -1.01584088 -1.01690805]
 [-0.94702253 -0.23054667 -1.01584088 -1.01690805]
 [-1.25067704  0.1886291  -1.08401812 -1.01690805]
 [-1.4025043  -0.02095879 -0.94766364 -1.01690805]
 [-0.79519527  1.02698063 -1.01584088 -1.01690805]
 [-0.18788623  1.65574428 -0.81130916 -0.67292224]
 [-1.4025043   0.60780486 -1.01584088 -0.84491515]
 [-0.79519527  0.60780486 -0.94766364 -1.01690805]
 [-1.70615882 -0.44013456 -1.01584088 -1.01690805]
 [-0.94702253 -0.02095879 -0.94766364 -1.18890096]
 [-0.18788623  1.23656851 -0.94766364 -1.01690805]
 [-1.09884979  0.60780486 -0.8794864  -1.01690805]
 [-1.09884979 -0.23054667 -1.01584088 -1.18890096]
 [-1.85798608 -0.23054667 -1.2203726  -1.18890096]
 [ 0.4194228   1.86533217 -1.15219536 -1.01690805]
 [ 0.26759554  2.7036837  -0.94766364 -0.67292224]
 [-0.18788623  1.65574428 -1.08401812 -0.67292224]
 [-0.64336801  0.81739275 -1.01584088 -0.84491515]
 [ 0.26759554  1.4461564  -0.81130916 -0.84491515]
 [-0.64336801  1.4461564  -0.94

In [6]:
y_train[:40],y_train[40:]=y[:40],y[50:90]
y_test[:10],y_test[10:]=y[40:50],y[90:100]
#print(y_train)

In [7]:
#define function
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [8]:
def activation(x,w,b):
    return sigmoid(np.dot(x,w)+b)

In [9]:
def update(x,y,w,b,eta):
    y_pred=activation(x, w, b)
    a=(y_pred-y_train)*y_pred*(1-y_pred)
    for i in range(4):
        w[i] -= eta*1/float(len(y))*np.sum(a*x[:,i])
    b -= eta*1/float(len(y))*np.sum(a)
    return w,b

In [10]:
#the initial value of w,b and eta
weights=np.ones(4)/10
bias=np.ones(1)/10
eta=0.1
#print(bias)

In [11]:
#update weight and bias
for _ in range(100):
    weights,bias=update(x_train,y_train,weights,bias,eta)
    
#print('weights=',weights,'bias=',bias)

In [12]:
#use test data to see the result
print(activation(x_test, weights, bias))

[0.16623357 0.2410168  0.13195789 0.2316736  0.19641579 0.20196296
 0.1513424  0.15154546 0.1711224  0.17607219 0.79878992 0.85360581
 0.80273053 0.65378822 0.80137688 0.76222751 0.7904257  0.84175434
 0.63373542 0.79448326]
